#!/usr/bin/env python3
"""Compile GOAL.md and OBSERVATION.md from machine state.

The prose files are PROJECTIONS, never sources. Operative facts — dates, thresholds,
weights, kill conditions, definitions — live in config/gates.json and config/survey.json,
which the tools actually read. This renders them into human-readable form so a person can
audit the machine's state without running anything; selfcheck (I12) fails the build if the
rendered output and the committed files disagree, so prose cannot drift into wishful thinking.

Usage: python3 tools/render.py [--check]   (--check exits 1 on drift, writes nothing)
"""
import json, sys, pathlib

ROOT = pathlib.Path(__file__).resolve().parent.parent
BANNER = ("<!-- GENERATED by tools/render.py from {src} — DO NOT EDIT THIS FILE.\n"
          "     Edit the JSON, re-run the renderer, commit both. CI check I12 fails on drift. -->\n")


def goal_md():
    g = json.loads((ROOT / "config" / "gates.json").read_text())
    L = [BANNER.format(src="config/gates.json"), "# The Goal", "",
         f"**Status: {'IN EFFECT' if g['in_effect'] else 'NOT IN EFFECT'} since {g['t0']} (T0). "
         f"Integrity violations to date: {g['integrity_violations_to_date']}.**", "",
         "## The goal, in one sentence", "", g["goal_one_line"], "",
         "## Graded terms", "", "| term | definition |", "|---|---|"]
    L += [f"| **{k}** | {v} |" for k, v in g["definitions"].items()]
    L += ["", "## Gates", "", "| gate | what must be true | due | kill condition if missed | status |",
          "|---|---|---|---|---|"]
    L += [f"| **{x['id']} — {x['title']}** | {x['pass_condition']} | {x['due']} | {x['kill_condition']} | {x['status']} |"
          for x in g["gates"]]
    L += ["", "Each gate's outcome is recorded as a journal event of the type named in "
              "`config/gates.json` (`result_event_type`); the dead-man's switch and the cross-session "
              "watchdog both look for exactly that event, so a gate that did not run is detectable "
              "without asking anyone.", "", "## Non-goals — named so they cannot creep in", ""]
    L += [f"- {n}" for n in g["non_goals"]]
    L += ["", "## Correction record", ""] + [f"- {c}" for c in g["correction_record"]]
    L += ["", "---", "*This page is compiled. `config/gates.json` is the state; if they disagree, "
              "CI check I12 fails and the JSON wins.*"]
    return "\n".join(L) + "\n"


def observation_md():
    s = json.loads((ROOT / "config" / "survey.json").read_text())
    L = [BANNER.format(src="config/survey.json"), f"# {s['phase']} — The Survey", "",
         f"**Machine state: `config/survey.json`. Sampling runs every {s['sample_cadence_hours']}h until "
         f"{s['survey_end_utc']} (enforced in `tools/sample.py`, which reads this file). "
         f"Decision at {s['decision_utc']}.**", "", "## The question", "", s["question"], "",
         "## Candidates", "", ", ".join(f"`{c}`" for c in s["candidates"]), "",
         "## Scoring criteria — weights fixed before the data", "", "| criterion | weight |", "|---|---|"]
    L += [f"| {k.replace('_', ' ')} | {int(v * 100)}% |" for k, v in s["criteria_weights"].items()]
    L += ["", f"Weights sum to {sum(s['criteria_weights'].values()):.2f} (CI check I13 fails otherwise).", "",
          "## Outcome definitions — computable, no discretion at grade time", "", "| class | test |", "|---|---|"]
    L += [f"| {k} | `{v}` |" for k, v in s["outcome_definitions"].items()]
    L += ["", "## Census thresholds — what the decision wake must do", "",
          f"- cohorts < **{s['census_thresholds']['gap_incident_below']}** → journal a sampling_gap incident",
          f"- cohorts < **{s['census_thresholds']['stop_survey_below']}** → STOP, journal insufficient-data, "
          f"append a `survey_extended` event (without it the sampler refuses to run past the end date)",
          "", "## Excluded by construction", ""]
    L += [f"- {e}" for e in s["excluded_by_construction"]]
    L += ["", "## Known limits, stated now", ""] + [f"- {k} lint-exempt" for k in s["known_limits"]]
    L += ["", "---", "*This page is compiled from `config/survey.json`. CI check I12 fails on drift.*"]
    return "\n".join(L) + "\n"


def readme_md():
    g = json.loads((ROOT / "config" / "gates.json").read_text())
    return (BANNER.format(src="config/gates.json + config/boot.json") +
            "# BBP\n\n"
            f"**Goal.** {g['goal_one_line']}\n\n"
            "**Boot.**\n\n```\npython3 tools/boot.py\n```\n\n"
            "Exit 0 prints the machine's computed state and your constraints. Exit 1 means an\n"
            "invariant is broken and fixing it is the only authorised work.\n\n"
            "Everything else in this repository is either machine state (`config/*.json`), an\n"
            "append-only record (`JOURNAL.jsonl`, `FORECASTS.jsonl`), a tool that enforces\n"
            "something, or a page compiled from those. No file here asks to be obeyed: the\n"
            "constraints that matter are executed by the tools and verified by CI, and the\n"
            "prose exists so a human can audit the machine without running it.\n")


def main():
    targets = {ROOT / "GOAL.md": goal_md(), ROOT / "OBSERVATION.md": observation_md(),
               ROOT / "README.md": readme_md()}
    drift = []
    for path, content in targets.items():
        if "--check" in sys.argv:
            if not path.exists() or path.read_text() != content:
                drift.append(path.name)
        else:
            path.write_text(content)
            print(f"rendered {path.name} ({len(content.splitlines())} lines)")
    if "--check" in sys.argv:
        if drift:
            print(f"DRIFT: {drift} do not match config — run python3 tools/render.py and commit")
            return 1
        print("no drift: compiled docs match machine state")
    return 0


if __name__ == "__main__":
    sys.exit(main())
