#!/usr/bin/env python3
"""Generate STATUS.md — the principal-facing control board.

STATUS.md is a COMPILED PROJECTION of JOURNAL.jsonl, FORECASTS.jsonl,
config/caps.json and data/. It is never hand-edited: a projection that is
computed cannot silently drift from the journal (it can only be stale, and
it prints its own generation time so staleness is visible). Regenerate with:
    python3 tools/status.py
"""
import json, sys, pathlib

ROOT = pathlib.Path(__file__).resolve().parent.parent
# Read from config/gates.json, never restated here. Four gate dates written in a second
# place are four dates waiting to disagree with the first (2026-08-21).
GATES = [(g["id"], g["title"], g["due"])
         for g in json.loads((ROOT / "config" / "gates.json").read_text())["gates"]]


def _body(text):
    """The comparable content of the board. Every line counts: the page is deterministic given
    journal and config state, so there is nothing volatile to exclude. Excluding a line from
    this comparison means changes to that line can never be detected as drift."""
    return text.splitlines()


def read_jsonl(p):
    if not p.exists():
        return []
    return [json.loads(l) for l in p.read_text().splitlines() if l.strip()]


def main():
    j = read_jsonl(ROOT / "JOURNAL.jsonl")
    f = read_jsonl(ROOT / "FORECASTS.jsonl")
    caps = json.loads((ROOT / "config" / "caps.json").read_text())
    cohorts = sorted((ROOT / "data" / "cohorts").glob("cohort_*.json"))
    complete = 0
    for c in cohorts:
        try:
            complete += 1 if json.loads(c.read_text()).get("completeness", {}).get("complete") else 0
        except Exception:
            pass
    snap_p = ROOT / "data" / "triggers_snapshot.json"
    snap = json.loads(snap_p.read_text()) if snap_p.exists() else None

    drills = [e for e in j if e["type"] == "drill_result"]
    # Explicit classification only: a drill counts as passed if its body says PASS and never
    # says FAIL. Anything else is UNCLASSIFIED and reported as such — a heuristic that silently
    # miscounts is worse than one that admits ignorance (found by red-team audit 2026-08-20).
    def _cls(e):
        b = e["body"].upper()
        if "FAIL" in b and "PASS" not in b:
            return "fail"
        return "pass" if "PASS" in b else "unclassified"
    drill_pass = sum(1 for e in drills if _cls(e) == "pass")
    drill_fail = sum(1 for e in drills if _cls(e) == "fail")
    drill_unc = sum(1 for e in drills if _cls(e) == "unclassified")
    incidents = [e for e in j if e["type"] == "incident"]
    risks = [e for e in j if e["type"] == "open_risk"]
    pending = [e for e in j if e["type"] == "principal_pending"]
    resolved_keys = {e["body"].split("|", 1)[0].strip() for e in j if e["type"] == "principal_resolved"}
    pending = [e for e in pending if e["body"].split("|", 1)[0].strip() not in resolved_keys]
    forecasts = [r for r in f if r.get("type") == "forecast"]
    grades = [r for r in f if r.get("type") == "grade"]

    L = []
    L.append("# BBP — Control Board")
    L.append("")
    # A staleness banner used to be computed here from j[-1]["ts"] via strptime("%Y-%m-%d").
    # Journal timestamps became full ISO on 2026-08-21, so it threw ValueError into a bare
    # except and the banner could never fire again - a dead check that still looked alive.
    # Removed: I10 detects staleness by regenerating and diffing, which does not rot.
    # This page is a PURE FUNCTION of journal + config state: no wall clock, no commit sha.
    # The header used to carry both. The sha was invalidated by the act of committing the page,
    # and the timestamp changed on every run, so the generator dirtied the working tree every
    # time it ran and `git status` stopped carrying information. Determinism also means the
    # I10 drift check compares the WHOLE file - the earlier version excluded the header from
    # comparison, which meant a change to the header format could never land.
    L.append(f"*Generated by `tools/status.py` — reflecting {len(j)} journal events through "
             f"`{j[-1]['ts'] if j else 'none'}`. Do not hand-edit: invariant I10 regenerates "
             "this page and fails CI if it differs.*")
    L.append("")
    L.append("## Where the firm is")
    L.append("")
    L.append("Phase 1 (H1.0 venue survey) — collecting on-chain data to decide where to forecast first. "
             "Zero capital at risk. Wallet allowance: "
             f"**${caps['total_capital_allowance_usd']}** (hard-capped until H1 passes).")
    L.append("")
    L.append("## Needs the principal")
    L.append("")
    if pending:
        for e in pending:
            key, _, body = e["body"].partition("|")
            L.append(f"- **{key.strip()}** — {body.strip()} *(journaled {e['ts']})*")
    else:
        L.append("- Nothing. The wakes are doing the working.")
    L.append("")
    L.append("## What happens next (scheduled, not aspirational)")
    L.append("")
    if snap:
        L.append(f"*Scheduler snapshot as of {snap['as_of']} — refreshed by interactive sessions; "
                 "the journal is the record of registrations between refreshes.*")
        L.append("")
        L.append("| when (UTC) | what | id |")
        L.append("|---|---|---|")
        for t in sorted(snap["triggers"], key=lambda x: x.get("next_run_at") or ""):
            L.append(f"| {t.get('next_run_at','?')} | {t['name']} | `{t['id'][:14]}…` |")
    L.append("")
    L.append("## Gates")
    L.append("")
    L.append("| gate | what | due | status |")
    L.append("|---|---|---|---|")
    for g, what, due in GATES:
        L.append(f"| {g} | {what} | {due} | pending |")
    L.append("")
    L.append("## Scoreboard (ugly numbers on the front page, per the rules)")
    L.append("")
    L.append(f"- Pre-registered forecasts: **{len(forecasts)}** · graded: **{len(grades)}** "
             "(H1 needs ≥100 graded; calibration currently **unproven — n too small to claim anything**)")
    L.append(f"- Survey cohorts collected: **{len(cohorts)}** — of which stamped complete: "
             f"**{complete}** (stamping began 2026-08-20; earlier cohorts are unstamped, not incomplete). "
             "Decision-wake threshold: <14 files journals a gap incident, <8 stops the survey")
    L.append(f"- Drills run: **{len(drills)}** — passed **{drill_pass}**, failed **{drill_fail}**, "
             f"unclassified **{drill_unc}** · Incidents: **{len(incidents)}** "
             f"(all incidents are public in JOURNAL.jsonl)")
    # Money line is computed or declared unknown — never asserted (red-team 2026-08-20: this line
    # hardcoded "envelope untouched" while overage credits had already been purchased).
    spend_events = [e for e in j if e["type"] == "principal_action" and "credit" in e["body"].lower()]
    L.append(f"- Revenue to date: **$0** (no revenue event in the journal) · Wallet capital deployed: "
             f"**$0** (allowance ${caps['total_capital_allowance_usd']}) · Envelope "
             f"**${caps['experiment_budget_usd_total']}**: **{len(spend_events)} principal credit "
             "purchase(s) journaled, dollar amounts NOT reported to the firm — envelope spend is "
             "therefore UNKNOWN, not zero**")
    L.append("")
    L.append("## Open risks (live, not archived)")
    L.append("")
    for e in risks:
        first = e["body"].split(".")[0]
        L.append(f"- {first}. *(journaled {e['ts']}; full text in JOURNAL.jsonl)* lint-exempt")
    L.append("")
    L.append("## Recent events (last 8 journal lines, newest last)")
    L.append("")
    for e in j[-8:]:
        # Not every event type carries 'status' or 'provenance'; a board generator that
        # KeyErrors on an unfamiliar event is a single-point failure for the sampler wake,
        # which runs this as step 4 (found 2026-08-21 while journaling a receipt defect).
        _tag = e.get("status") or e.get("provenance") or "-"
        L.append(f"- `{e['ts']}` **{e['type']}** ({_tag}) — {e['body'][:160]}{'…' if len(e['body'])>160 else ''} lint-exempt")
    L.append("")
    L.append("---")
    L.append("*Ground truth is `JOURNAL.jsonl`; where this page and the journal disagree, the journal wins. "
             "Docs: `GOAL.md` (what/gates) · `STRATEGY.md` (how) · `OBSERVATION.md` (current survey) · "
             "`PRINCIPLES.md` (rules).*")
    text = "\n".join(L) + "\n"
    dest = ROOT / "STATUS.md"
    if "--check" in sys.argv:
        # Freshness by DRIFT, not by clock. I10 used to compare the board's date string to the
        # newest journal timestamp; both were date-only, so any staleness inside a single day
        # read as fresh, and the check only ever fired across a midnight boundary. Comparing
        # the generated body to the committed body has no clock semantics to get wrong.
        cur = dest.read_text() if dest.exists() else ""
        if _body(cur) == _body(text):
            print("board matches journal state")
            return 0

        print("STALE: STATUS.md does not match what tools/status.py generates from current "
              "journal state. Run: python3 tools/status.py", file=sys.stderr)
        return 1
    # Do not rewrite when only the header would move: a generator that dirties the working
    # tree on every no-op run trains everyone to ignore `git status`, and the stop-hook that
    # caught this was reporting a real uncommitted change that carried no information.
    if dest.exists() and _body(dest.read_text()) == _body(text):
        print(f"STATUS.md already current ({len(L)} lines, unchanged)")
        return 0
    dest.write_text(text)
    print(f"STATUS.md generated ({len(L)} lines)")
    return 0


if __name__ == "__main__":
    sys.exit(main() or 0)
