#!/usr/bin/env python3
"""Generate STATUS.md — the principal-facing control board.

STATUS.md is a COMPILED PROJECTION of JOURNAL.jsonl, FORECASTS.jsonl,
config/caps.json and data/. It is never hand-edited: a projection that is
computed cannot silently drift from the journal (it can only be stale, and
it prints its own generation time so staleness is visible). Regenerate with:
    python3 tools/status.py
"""
import json, datetime, pathlib, subprocess

ROOT = pathlib.Path(__file__).resolve().parent.parent
GATES = [("G0", "Plumbing proven", "2026-09-17"), ("G1", "First verified dollar", "2026-11-17"),
         ("G2", "Positive unit economics", "2027-02-17"), ("G3", "Sustainability", "2027-08-17")]


def read_jsonl(p):
    if not p.exists():
        return []
    return [json.loads(l) for l in p.read_text().splitlines() if l.strip()]


def main():
    now = datetime.datetime.now(datetime.timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    j = read_jsonl(ROOT / "JOURNAL.jsonl")
    f = read_jsonl(ROOT / "FORECASTS.jsonl")
    caps = json.loads((ROOT / "config" / "caps.json").read_text())
    try:
        sha = subprocess.run(["git", "rev-parse", "--short", "HEAD"], cwd=ROOT,
                             capture_output=True, text=True).stdout.strip()
    except Exception:
        sha = "unknown"
    cohorts = sorted((ROOT / "data" / "cohorts").glob("cohort_*.json"))
    snap_p = ROOT / "data" / "triggers_snapshot.json"
    snap = json.loads(snap_p.read_text()) if snap_p.exists() else None

    drills = [e for e in j if e["type"] == "drill_result"]
    # Explicit classification only: a drill counts as passed if its body says PASS and never
    # says FAIL. Anything else is UNCLASSIFIED and reported as such — a heuristic that silently
    # miscounts is worse than one that admits ignorance (found by red-team audit 2026-08-20).
    def _cls(e):
        b = e["body"].upper()
        if "FAIL" in b and "PASS" not in b:
            return "fail"
        return "pass" if "PASS" in b else "unclassified"
    drill_pass = sum(1 for e in drills if _cls(e) == "pass")
    drill_fail = sum(1 for e in drills if _cls(e) == "fail")
    drill_unc = sum(1 for e in drills if _cls(e) == "unclassified")
    incidents = [e for e in j if e["type"] == "incident"]
    risks = [e for e in j if e["type"] == "open_risk"]
    pending = [e for e in j if e["type"] == "principal_pending"]
    resolved_keys = {e["body"].split("|", 1)[0].strip() for e in j if e["type"] == "principal_resolved"}
    pending = [e for e in pending if e["body"].split("|", 1)[0].strip() not in resolved_keys]
    forecasts = [r for r in f if r.get("type") == "forecast"]
    grades = [r for r in f if r.get("type") == "grade"]

    L = []
    L.append("# BBP — Control Board")
    L.append("")
    lag_h = None
    if j:
        try:
            last = datetime.datetime.strptime(j[-1]["ts"], "%Y-%m-%d").replace(tzinfo=datetime.timezone.utc)
            lag_h = (datetime.datetime.now(datetime.timezone.utc) - last).total_seconds() / 3600
        except Exception:
            pass
    L.append(f"*Generated by `tools/status.py` at **{now}** from journal state at commit `{sha}` — "
             "do not hand-edit. If this page looks stale, it is: the generation time above is the honesty mechanism.*")
    if lag_h is not None and lag_h > 30:
        L.append("")
        L.append(f"> **STALE — regenerate.** The newest journal entry is ~{lag_h:.0f}h older than nothing "
                 "regenerated since. Any session touching this repo should run `python3 tools/status.py` and commit.")
    L.append("")
    L.append("## Where the firm is")
    L.append("")
    L.append("Phase 1 (H1.0 venue survey) — collecting on-chain data to decide where to forecast first. "
             "Zero capital at risk. Wallet allowance: "
             f"**${caps['total_capital_allowance_usd']}** (hard-capped until H1 passes).")
    L.append("")
    L.append("## Needs the principal")
    L.append("")
    if pending:
        for e in pending:
            key, _, body = e["body"].partition("|")
            L.append(f"- **{key.strip()}** — {body.strip()} *(journaled {e['ts']})*")
    else:
        L.append("- Nothing. The wakes are doing the working.")
    L.append("")
    L.append("## What happens next (scheduled, not aspirational)")
    L.append("")
    if snap:
        L.append(f"*Scheduler snapshot as of {snap['as_of']} — refreshed by interactive sessions; "
                 "the journal is the record of registrations between refreshes.*")
        L.append("")
        L.append("| when (UTC) | what | id |")
        L.append("|---|---|---|")
        for t in sorted(snap["triggers"], key=lambda x: x.get("next_run_at") or ""):
            L.append(f"| {t.get('next_run_at','?')} | {t['name']} | `{t['id'][:14]}…` |")
    L.append("")
    L.append("## Gates")
    L.append("")
    L.append("| gate | what | due | status |")
    L.append("|---|---|---|---|")
    for g, what, due in GATES:
        L.append(f"| {g} | {what} | {due} | pending |")
    L.append("")
    L.append("## Scoreboard (ugly numbers on the front page, per the rules)")
    L.append("")
    L.append(f"- Pre-registered forecasts: **{len(forecasts)}** · graded: **{len(grades)}** "
             "(H1 needs ≥100 graded; calibration currently **unproven — n too small to claim anything**)")
    L.append(f"- Survey cohorts collected: **{len(cohorts)}** (decision expects ~20 by 2026-08-24)")
    L.append(f"- Drills run: **{len(drills)}** — passed **{drill_pass}**, failed **{drill_fail}**, "
             f"unclassified **{drill_unc}** · Incidents: **{len(incidents)}** "
             f"(all incidents are public in JOURNAL.jsonl)")
    L.append(f"- Revenue to date: **$0** · Capital deployed: **$0** · Budget envelope: "
             f"**${caps['experiment_budget_usd_total']}** (untouched)")
    L.append("")
    L.append("## Open risks (live, not archived)")
    L.append("")
    for e in risks:
        first = e["body"].split(".")[0]
        L.append(f"- {first}. *(journaled {e['ts']}; full text in JOURNAL.jsonl)*")
    L.append("")
    L.append("## Recent events (last 8 journal lines, newest last)")
    L.append("")
    for e in j[-8:]:
        L.append(f"- `{e['ts']}` **{e['type']}** ({e['status']}) — {e['body'][:160]}{'…' if len(e['body'])>160 else ''}")
    L.append("")
    L.append("---")
    L.append("*Ground truth is `JOURNAL.jsonl`; where this page and the journal disagree, the journal wins. "
             "Docs: `GOAL.md` (what/gates) · `STRATEGY.md` (how) · `OBSERVATION.md` (current survey) · "
             "`PRINCIPLES.md` (rules).*")
    (ROOT / "STATUS.md").write_text("\n".join(L) + "\n")
    print(f"STATUS.md generated ({len(L)} lines)")


if __name__ == "__main__":
    main()
